# Generated by Django 3.2 on 2021-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturalarapp', '0003_alter_faturalar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturalar',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
