# Generated by Django 3.2 on 2021-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturalarapp', '0004_alter_faturalar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturalar',
            name='username',
            field=models.IntegerField(blank=True),
        ),
    ]
