# Generated by Django 3.2 on 2021-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturalarapp', '0005_alter_faturalar_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturalar',
            old_name='title',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='faturalar',
            old_name='description',
            new_name='fiyat',
        ),
        migrations.RenameField(
            model_name='faturalar',
            old_name='username',
            new_name='kullanici',
        ),
        migrations.RenameField(
            model_name='faturalar',
            old_name='finished',
            new_name='odendi',
        ),
        migrations.RenameField(
            model_name='faturalar',
            old_name='date',
            new_name='tarih',
        ),
    ]
